"""
Seed fixtures - GENERATED FILE, DO NOT EDIT BY HAND.

Exported from a live database on 2026-08-22 01:40 UTC by
`python -m scripts.export_seed_data`, and replayed by
`python -m scripts.seed_catalog`. Hand edits are lost the next time somebody
re-exports; change the data in the database and export again instead.

Every reference between tables is a natural key ("brand", "category",
"product" hold names, not ids) - see the module docstring in
scripts/export_seed_data.py for why.
"""
from datetime import datetime, timezone

BRANDS = [
    {"brand_name": "Woodpecker", "brand_image": "/static/uploads/brands/cdc69b77c9fd40b380a147adadb3fa66.png"},
    {"brand_name": "YouJoy", "brand_image": "/static/uploads/brands/64722a7c1fa14ea0aede420c65c2a09a.png"},
    {"brand_name": "Asus", "brand_image": "/static/uploads/brands/23b6acb395694361a07d3ecf008f3536.png"},
    {"brand_name": "Lenovo", "brand_image": "/static/uploads/brands/a2a4a77bdd8345eea17ed0bf0cc09f1e.png"},
]


CATEGORIES = [
    {"category_name": "Diode Laser System", "category_image": None},
    {"category_name": "Intraoral Scanner", "category_image": None},
    {"category_name": "Piezo Bone Surgery", "category_image": None},
    {"category_name": "Dental Implant Device", "category_image": None},
    {"category_name": "Dental Electric Motor", "category_image": None},
    {"category_name": "Air Polisher System", "category_image": None},
    {"category_name": "Endo Activator", "category_image": None},
    {"category_name": "Endo Motor", "category_image": None},
    {"category_name": "Gutta-purcha Obteration System", "category_image": None},
    {"category_name": "Curing Light", "category_image": None},
    {"category_name": "Ultrasonic Scaler", "category_image": None},
    {"category_name": "Air polisher", "category_image": None},
    {"category_name": "Portable X-ray", "category_image": None},
    {"category_name": "KP-Oral Camera Combo Set", "category_image": None},
    {"category_name": "Laptop", "category_image": None},
    {"category_name": "Apex Locator", "category_image": None},
    {"category_name": "Student Kit", "category_image": None},
    {"category_name": "Trolley", "category_image": None},
    {"category_name": "Surgical Microscope", "category_image": None},
    {"category_name": "Intraoral Camera", "category_image": None},
    {"category_name": "Contra-angles", "category_image": None},
    {"category_name": "Contra-angles for implant Motor", "category_image": None},
    {"category_name": "Contra-angles Endo Motor", "category_image": None},
    {"category_name": "Color Shade Detector", "category_image": None},
    {"category_name": "Autoclave", "category_image": None},
    {"category_name": "Ultrasonic Cleaner", "category_image": None},
    {"category_name": "Dental Sensor", "category_image": None},
    {"category_name": "Water Distiller", "category_image": None},
    {"category_name": "Sealing Machine", "category_image": None},
    {"category_name": "Air Compressor", "category_image": None},
    {"category_name": "Mobile Cart", "category_image": None},
    {"category_name": "Suction Unit", "category_image": None},
    {"category_name": "Accessories", "category_image": None},
    {"category_name": "Computers", "category_image": None},
]


# "brand" / "category" are names resolved against BRANDS / CATEGORIES above.
# "images" are the EXTRA gallery photos only - the primary one is
# product_image. "free_items" name other products in this same list, so
# they are linked in a second pass once every product exists.
PRODUCTS = [
    {"product_name": "LX16-PLUS", "description": "Multi-purpose dental diode laser for soft tissue, perio, endo, implant, surgery, and pain therapy.", "price": 0.01, "list_price": 3480, "discount": 3479.99, "discount_type": "cash", "brand": "Woodpecker", "category": "Diode Laser System", "product_code": None, "uom": None, "badge": "new", "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/LX16-PLUS image.JPEG",
        "images": [],
        "free_items": [
            {"product": "Woodpecker Trolley", "qty": 1},
            {"product": "WJ-SG45CL (1:3)", "qty": 1},
        ],
    },
    {"product_name": "KP SmileScan", "description": "High-precision intraoral scanner with full-arch imaging, AI-enhanced accuracy, and seamless lab integration.", "price": 3372.5, "list_price": 3550, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Intraoral Scanner", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/KP SmileScan image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "US-II LED", "description": "Multi-function piezo ultrasonic scaler for scaling, perio, endo, implant maintenance, and surgery.", "price": 1425, "list_price": 1500, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Piezo Bone Surgery", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/US-II LED image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Implanter", "description": "Precision implant motor for implant placement, surgery, and torque control.", "price": 1235, "list_price": 1300, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Implant Device", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Implanter image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Surgery-X", "description": "Piezoelectric surgical unit for bone surgery, soft tissue surgery, and implant placement with adjustable power and irrigation.", "price": 2470, "list_price": 2600, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Piezo Bone Surgery", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Surgery-X image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "3 in 1 Surgic Star", "description": "3-in-1 premium implant and surgical motor with smart presets, touchscreen control, and stable irrigation.", "price": 3705, "list_price": 3900, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Implant Device", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/3 in 1 Surgic Star image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "ES5", "description": "High-performance multi-purpose electric motor for implant, surgical, and endodontic procedures, up to 120,000 rpm.", "price": 1520, "list_price": 1600, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Electric Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/ES5 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "PT-A", "description": "Ultrasonic scaler and air polisher combo with heated water delivery and hands-free touchscreen control.", "price": 2470, "list_price": 2600, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Air Polisher System", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/PT-A image.JPEG",
        "images": [],
        "free_items": [
            {"product": "Supragingical Prophylaxis Powder", "qty": 3},
        ],
    },
    {"product_name": "Endo 3", "description": "High-performance rotary endodontic system for root canal treatment, cleaning, and shaping.", "price": 171, "list_price": 180, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Activator", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Endo 3 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Endo Radar Pro", "description": "Top-tier apex locator with advanced tracking technology for precise root canal measurement.", "price": 456, "list_price": 480, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Endo Radar Pro image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "FI-G", "description": "Gutta percha obturation device with exceptional sealing performance and easy handling.", "price": 289.8, "list_price": 305.05, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Gutta-purcha Obteration System", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/FI-G image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Motopex", "description": "Compact dental micromotor for precision drilling, root canal treatment, implantology, and crown prep.", "price": 399, "list_price": 420, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Motopex image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "FI-P", "description": "Gutta percha obturation device with superior adaptability and long-term reliability.", "price": 180.5, "list_price": 190, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Gutta-purcha Obteration System", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/FI-P image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "E-COM+", "description": "Powerful cordless endomotor for canal cleaning and shaping with precise torque control.", "price": 275.5, "list_price": 290, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/E-COM+ image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "R1-Plus", "description": "Precision endodontic measuring ruler for gutta percha cutting and working length measurement.", "price": 25, "list_price": 29.07, "discount": 14, "discount_type": "percent", "brand": "Woodpecker", "category": "Gutta-purcha Obteration System", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/R1-Plus image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Endo Pace", "description": "Cordless brushless endomotor with apex locator integration for safe, efficient canal treatment.", "price": 256.5, "list_price": 270, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Endo Pace image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED H", "description": "Curing light, light intensity 1000-1800 mW/cm2.", "price": 104.5, "list_price": 110, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/LED H image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED F", "description": "Curing light, light intensity 1600-1800 mW/cm2.", "price": 128.3, "list_price": 135.05, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/LED F image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED G", "description": "Curing light, light intensity 1000-1200 mW/cm2.", "price": 66.5, "list_price": 70, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/LED G image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED B", "description": "Curing light, light intensity 1000-1700 mW/cm2.", "price": 54.4, "list_price": 68, "discount": 20, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/LED B image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "iLED II", "description": "Curing light, light intensity 2700-3000 mW/cm2.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/iLED II image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "U-Light", "description": "Lightweight curing light with 3 modes and 360° rotation for consistent polymerization.", "price": 171, "list_price": 180, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/U-Light image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "iLED MAX", "description": "Curing light, light intensity 2300-2500 mW/cm2.", "price": 116, "list_price": 119.59, "discount": 3, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/iLED MAX image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "O-Star", "description": "High-performance curing light with 7 preset modes and 360° use for deep polymerization.", "price": 342, "list_price": 360, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/O-Star image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "iLED Plus", "description": "Curing light, light intensity 2300-2500 mW/cm2.", "price": 95, "list_price": 100, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/iLED Plus image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "U600 LED", "description": "Advanced ultrasonic scaler with LED handpiece illumination and 3 modes (scaling, perio, endo).", "price": 332.5, "list_price": 350, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/U600 LED image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N3 LED", "description": "Built-in ultrasonic scaler with LED illumination and detachable autoclavable handpiece.", "price": 115, "list_price": 115, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/UDS-N3 LED image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-T LED", "description": "Multi-function ultrasonic scaler for scaling, perio, and endo with LED handpiece.", "price": 247, "list_price": 260, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/UDS-T LED image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N6", "description": "Compact built-in scaler for scaling, perio, and endo with auto frequency tracking.", "price": 179, "list_price": 179, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/UDS-N6 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "USD-E LED", "description": "Precision ultrasonic scaler with adjustable power and bright LED illumination.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/USD-E LED image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N3 LED Handpiece", "description": "Replacement handpiece for the UDS-N3 LED ultrasonic scaler.", "price": 69, "list_price": 69, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/UDS-N3 LED Handpiece image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N6 LED Handpiece", "description": "Replacement handpiece for the UDS-N6 LED ultrasonic scaler.", "price": 81, "list_price": 81, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/UDS-N6 LED Handpiece image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "AP-H", "description": "High-performance dental air polisher for stain removal, whitening, prophylaxis, and implant cleaning.", "price": 179.6, "list_price": 189.05, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Air polisher", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/AP-H image.JPEG",
        "images": [],
        "free_items": [
            {"product": "Supragingical Prophylaxis Powder", "qty": 1},
        ],
    },
    {"product_name": "i-Sensor H2", "description": "High-resolution digital intraoral sensor for adult imaging with AI-enhanced diagnostics.", "price": 750.5, "list_price": 790, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Sensor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/i-Sensor H2 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro", "description": "High-speed 3D scanner for quality inspection, reverse engineering, and precision measurement.", "price": 665, "list_price": 700, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Smart Ray Pro image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "i-Sensor H 1.5", "description": "High-resolution digital intraoral sensor for adult imaging with AI-enhanced diagnostics.", "price": 655.5, "list_price": 690, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Sensor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/i-Sensor H 1.5 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Ray", "description": "AI-driven dental imaging system for diagnostics, treatment planning, and radiography.", "price": 845.5, "list_price": 890, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/AI-Ray image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Ray Pro", "description": "AI positioning X-ray system that automatically detects and aligns the target for consistent imaging.", "price": 997.5, "list_price": 1050, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/AI-Ray Pro image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray", "description": "Portable DC X-ray system for intraoral imaging, endodontic diagnosis, and implant planning.", "price": 703, "list_price": 740, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Smart Ray image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Pex (Master Version)", "description": "Advanced AI-powered apex locator plus pulp testing function for precise root canal measurement.", "price": 361, "list_price": 380, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/AI-Pex (Master Version) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Pex", "description": "Advanced AI-powered apex locator plus pulp testing function for precise root canal measurement.", "price": 342, "list_price": 360, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/AI-Pex image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Woodpex V", "description": "State-of-the-art apex locator ensuring accurate measurement for precise root canal treatments.", "price": 133, "list_price": 140, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Woodpex V image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Woodpex X", "description": "Compact, accurate apex locator for root canal length measurement and real-time canal monitoring.", "price": 180.5, "list_price": 190, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Woodpex X image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Mini-Pex", "description": "Portable, precise apex locator designed for accurate root canal measurement (student kit).", "price": 99, "list_price": 139.44, "discount": 29, "discount_type": "percent", "brand": "Woodpecker", "category": "Student Kit", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Mini-Pex image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Tampered Glass Trolley", "description": "Mobile organized cart with 360° mobility, secure storage, and cable management; includes 2 free trays.", "price": 266, "list_price": 280, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Tampered Glass Trolley image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "NW-A01", "description": "Mobile monitor cart with 360° mobility, secure storage, and cable management.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/NW-A01 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley 3-Drawer", "description": "Mobile organized cart with 360° mobility and secure storage; includes 2 free trays.", "price": 285, "list_price": 300, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Trolley 3-Drawer image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley T3-4", "description": "Multi-layer mobile dental trolley with 3-tier storage, lockable wheels, medical-grade structure.", "price": 123.5, "list_price": 130, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Trolley T3-4 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Woodpecker Trolley", "description": "Mobile organized cart designed to support Woodpecker devices with 360° mobility.", "price": 199.5, "list_price": 210, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Woodpecker Trolley image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley T3-2", "description": "Multi-layer mobile dental trolley with 3-tier design, lockable wheels, medical-grade structure.", "price": 95, "list_price": 100, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Trolley T3-2 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley NW-A03", "description": "Compact multi-drawer dental trolley with lockable wheels and flexible storage layout.", "price": 161.5, "list_price": 170, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Trolley NW-A03 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 66x44mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 55.1, "list_price": 58, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 66x44mm image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 600mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 75.05, "list_price": 79, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 600mm image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 60x40mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 49.4, "list_price": 52, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 60x40mm image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 500mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 69.35, "list_price": 73, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 500mm image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 30x40mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 36.1, "list_price": 38, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 30x40mm image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 40x60mm (3-tier)", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 56.05, "list_price": 59, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 40x60mm (3-tier) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 30x40mm (3-tier)", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 45.6, "list_price": 48, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Instrument Cart 30x40mm (3-tier) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "KP iSee Pro", "description": "Premium surgical dental microscope with German SCHOTT optics, inclinable binocular tube, and integrated 4K imaging.", "price": 10600, "list_price": 10600, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Surgical Microscope", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/KP iSee Pro image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "KP Cam Pro (Metal)", "description": "High-definition 1080P intraoral camera with one-click capture, true color reproduction, and 10 LED illumination.", "price": 940.5, "list_price": 990, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Intraoral Camera", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/KP Cam Pro (Metal) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "KP Cam Pro (Plastic)", "description": "High-definition 1080P intraoral camera with one-click capture, true color reproduction, and 10 LED illumination.", "price": 750.5, "list_price": 790, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Intraoral Camera", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/KP Cam Pro (Plastic) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-45TL (1:5)", "description": "Contra-angle handpiece, gear ratio 1:5.", "price": 220, "list_price": 220, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/WJ-45TL (1-5) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-45L (1:4.2)", "description": "Contra-angle handpiece, gear ratio 1:4.2.", "price": 365, "list_price": 365, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/WJ-45L (1-4.2) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-SG45CL (1:3)", "description": "Contra-angle handpiece, gear ratio 1:3.", "price": 340, "list_price": 340, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/WJ-SG45CL (1-3) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "WP-1L (20:1)", "description": "Contra-angle for implant motor, 20:1 reduction ratio, German bearing option available.", "price": 360, "list_price": 360, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles for implant Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/WP-1L (20-1) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "CA161 (6:1)", "description": "Contra-angle for endo motor, 6:1 reduction ratio.", "price": 169, "list_price": 169, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/CA161 (6-1) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "CA001-G", "description": "Contra-angle for endo motor.", "price": 98, "list_price": 98, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/CA001-G image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-11L(1:1)", "description": "Contra-angle for endo motor with Woodpecker bearing option.", "price": 210, "list_price": 210, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles Endo Motor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/WJ-11L(1-1) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "OMNI", "description": "Youjoy Omni Color Shade Detector for fast, accurate shade matching in crown, veneer, and restoration work.", "price": 266, "list_price": 280, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Color Shade Detector", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/OMNI image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "SCAN11", "description": "Youjoy Scan11 Intraoral Scanner - fast 3D intraoral scanning with cloud functions for easy data storage and transfer.", "price": 2300, "list_price": 2300, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Intraoral Scanner", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/SCAN11 image.JPEG",
        "images": [],
        "free_items": [
            {"product": "MOBILE CART TR/7A", "qty": 1},
            {"product": "ZIRCONIA Teeth Set", "qty": 5},
        ],
    },
    {"product_name": "BES 22L-CLASS-B-LCD", "description": "Youjoy BES-22L Class B LCD Autoclave sterilizer with clear LCD display for accurate, safe, and internationally compliant sterilization.", "price": 1580, "list_price": 1580, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/BES 22L-CLASS-B-LCD image.JPEG",
        "images": [],
        "free_items": [
            {"product": "DRINK (Water Distiller)", "qty": 1},
        ],
    },
    {"product_name": "BES 23L-CLASS-B-LCD", "description": "Youjoy BES-23L Class B autoclave sterilizer with LCD display, 121C/134C cycles, built-in USB data logging, B&D/Helix and leak test programs, double door lock system, and open water tank. Capacity: 23 L. Comes with a free water distiller and sealing machine.", "price": 1680, "list_price": 1680, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/BES 23L-CLASS-B-LCD image.JPEG",
        "images": [],
        "free_items": [
            {"product": "DRINK (Water Distiller)", "qty": 1},
            {"product": "SEAL120", "qty": 1},
        ],
    },
    {"product_name": "BES 23L-CLASS-B-LED", "description": "Youjoy BES-23L Class B autoclave sterilizer with LED display, 121C/134C cycles, built-in USB data logging, B&D/Helix and leak test programs, and double door lock system. Capacity: 23 L. Comes with a free water distiller and sealing machine; the rack version of the sealing machine is an extra $19.", "price": 1600, "list_price": 1600, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/BES 23L-CLASS-B-LED image.JPEG",
        "images": [],
        "free_items": [
            {"product": "DRINK (Water Distiller)", "qty": 1},
            {"product": "SEAL120", "qty": 1},
        ],
    },
    {"product_name": "UC-01", "description": "Youjoy Ultrasonic Cleaner UC-01 for fast, effective, and safe ultrasonic cleaning of dental instruments, jewelry, and medical tools. Capacity: 3 L.", "price": 179.55, "list_price": 189, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Ultrasonic Cleaner", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/UC-01 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "CLEAN-02", "description": "Youjoy Ultrasonic Cleaner UC-02, an advanced ultrasonic cleaner for dental instruments, jewelry, and medical tools. Capacity: 6 L.", "price": 280.25, "list_price": 295, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Ultrasonic Cleaner", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/CLEAN-02 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "CLEAN-03", "description": "Youjoy Ultrasonic Cleaner UC-03, a high-performance ultrasonic cleaner for dental instruments, jewelry, and medical tools. Capacity: 7.5 L.", "price": 418, "list_price": 440, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Ultrasonic Cleaner", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/CLEAN-03 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "R2", "description": "Youjoy Sensor R2, a digital dental sensor for dental X-ray imaging.", "price": 655.5, "list_price": 690, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Dental Sensor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/R2 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "DRINK (Water Distiller)", "description": "Youjoy Water Distiller (Model DRINK), a high-efficiency water distiller designed for dental clinics, medical offices, and laboratory use.", "price": 114, "list_price": 120, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Water Distiller", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/DRINK (Water Distiller) image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "YOUJOY98P", "description": "Youjoy 98P Portable Dental X-Ray for diagnosis, implant, and endo work, offering clear imaging and precise, easy-to-use portable operation. Tube voltage 70KV+-10%, tube current 2mA+-20%, focus 0.4mm, exposure time range 0.04s-2.0s, machine weight 1.9kg.", "price": 560.5, "list_price": 590, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/YOUJOY98P image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "SUPER05", "description": "Youjoy Super05 Portable X-Ray, a high-performance portable dental X-ray for diagnosis, endo, and implant planning. Tube voltage 70KV+-10%, tube current 2mA+-20%, focus 0.4mm, exposure time range 0.04s-2.0s, machine weight 1.7kg.", "price": 655.5, "list_price": 690, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/SUPER05 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "SEAL120", "description": "Youjoy SEAL120 Sealing Machine, a reliable sterilization pouch sealing machine designed for dental and medical clinics.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Sealing Machine", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/SEAL120 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "SEAL120 WITH RACK", "description": "Youjoy SEAL120 with rack Sealing Machine, a reliable sterilization pouch sealing machine designed for dental and medical clinics, including a rack.", "price": 170.05, "list_price": 179, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Sealing Machine", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/SEAL120 WITH RACK image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT30", "description": "Runyes Giant-30 compact oil-free dental 100% dry air supply system designed for stable and hygienic airflow. Capacity 25 L, 1400 RPM, 0.6 rated power (KVA), supports 1 chair.", "price": 380, "list_price": 400, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT30 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT35", "description": "Runyes Giant-35 Air Compressor, a powerful dual-pump oil-free dental 100% dry air system for 1-2 chairs. Capacity 50 L, 1400 RPM, 1.2 rated power (KVA), supports 2 chairs.", "price": 551, "list_price": 580, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT35 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT40", "description": "Runyes Giant-40 Air Compressor, a high-capacity oil-free dental 100% dry air system for up to 3 chairs. Capacity 60 L, 1400 RPM, 1.54 rated power (KVA), supports 3 chairs.", "price": 817, "list_price": 860, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT40 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT45", "description": "Runyes Giant-45 Air Compressor, a high-output oil-free dental 100% dry air system built for busy clinics. Capacity 70 L, 1400 RPM, 2.2 rated power (KVA), supports 5 chairs.", "price": 1349, "list_price": 1420, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT45 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT50", "description": "Runyes Giant-50 powerhouse oil-free 100% dry air compressor built for busy dental clinics. Capacity 135 L, 1400 RPM, 3.1 rated power (KVA), supports 8 chairs.", "price": 1824, "list_price": 1920, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT50 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT55", "description": "Runyes Giant-55 powerhouse oil-free 100% dry air compressor built for busy dental clinics. Capacity 210 L, 1400 RPM, 4.7 rated power (KVA), supports 12 chairs.", "price": 3610, "list_price": 3800, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT55 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "MOBILE CART TR/7A", "description": "TR-7A All-In-One Mobile Dental Cart, a sleek and versatile mobile workstation for digital dentistry with adjustable height, 3-layer tray design, 360-degree lockable wheels, and a built-in shelf for a laptop or scanner.", "price": 266, "list_price": 280, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Mobile Cart", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/MOBILE CART TR-7A image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "TR/7A WORKSTATION CART", "description": "TR-7A All-In-One Mobile Dental Cart, a sleek and versatile mobile workstation for digital dentistry with adjustable height, 3-layer tray design, 360-degree lockable wheels, and a dedicated VESA-compatible monitor mount for a screen or digital scanner.", "price": 370.5, "list_price": 390, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Mobile Cart", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/TR-7A WORKSTATION CART image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "BES 45L-CLASS-B-LCD", "description": "Youjoy BES-45L Class B autoclave sterilizer with touch-screen LCD display, 121C/134C cycles, built-in USB data logging, B&D/Helix and leak test programs, automatic locking system, and open water tank. Capacity: 45 L. Comes with a free water distiller and sealing machine.", "price": 3200, "list_price": 3200, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/BES 45L-CLASS-B-LCD image.JPEG",
        "images": [],
        "free_items": [
            {"product": "DRINK (Water Distiller)", "qty": 1},
            {"product": "SEAL120", "qty": 1},
        ],
    },
    {"product_name": "BES 18L-CLASS-B-LCD", "description": "Youjoy BES-18L Class B autoclave sterilizer with LCD display, 121C/134C cycles, built-in USB data logging, B&D/Helix and leak test programs, double door lock system, and open water tank. Capacity: 18 L. Comes with a free water distiller and sealing machine.", "price": 1630, "list_price": 1630, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/BES 18L-CLASS-B-LCD image.JPEG",
        "images": [],
        "free_items": [
            {"product": "DRINK (Water Distiller)", "qty": 1},
            {"product": "SEAL120", "qty": 1},
        ],
    },
    {"product_name": "BES 18L-CLASS-B-LED", "description": "Youjoy BES-18L Class B autoclave sterilizer with LED display, 121C/134C cycles, built-in USB data logging, B&D/Helix and leak test programs, double door lock system, and open water tank. Capacity: 18 L. Comes with a free water distiller and sealing machine; the rack version of the sealing machine is an extra $19.", "price": 1550, "list_price": 1550, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/BES 18L-CLASS-B-LED image.JPEG",
        "images": [],
        "free_items": [
            {"product": "DRINK (Water Distiller)", "qty": 1},
            {"product": "SEAL120", "qty": 1},
        ],
    },
    {"product_name": "GIANT30 WITH DRYER", "description": "Runyes Giant-30 compact oil-free dental 100% dry air supply system designed for stable and hygienic airflow, supplied with an air dryer. Capacity 25 L, 1400 RPM, 0.6 rated power (KVA), supports 1 chair.", "price": 522.5, "list_price": 550, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT30 WITH DRYER image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT35 WITH DRYER", "description": "Runyes Giant-35 Air Compressor, a powerful dual-pump oil-free dental 100% dry air system for 1-2 chairs, supplied with an air dryer. Capacity 50 L, 1400 RPM, 1.2 rated power (KVA), supports 2 chairs.", "price": 845.5, "list_price": 890, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT35 WITH DRYER image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT40 WITH DRYER", "description": "Runyes Giant-40 Air Compressor, a high-capacity oil-free dental 100% dry air system for up to 3 chairs, supplied with an air dryer. Capacity 60 L, 1400 RPM, 1.54 rated power (KVA), supports 3 chairs.", "price": 1140, "list_price": 1200, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT40 WITH DRYER image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT45 WITH DRYER", "description": "Runyes Giant-45 Air Compressor, a high-output oil-free dental 100% dry air system built for busy clinics, supplied with an air dryer. Capacity 70 L, 1400 RPM, 2.2 rated power (KVA), supports 5 chairs.", "price": 1710, "list_price": 1800, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT45 WITH DRYER image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT50 WITH DRYER", "description": "Runyes Giant-50 powerhouse oil-free 100% dry air compressor built for busy dental clinics, supplied with an air dryer. Capacity 135 L, 1400 RPM, 3.1 rated power (KVA), supports 8 chairs.", "price": 2185, "list_price": 2300, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT50 WITH DRYER image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT55 WITH DRYER", "description": "Runyes Giant-55 powerhouse oil-free 100% dry air compressor built for busy dental clinics, supplied with an air dryer. Capacity 210 L, 1400 RPM, 4.7 rated power (KVA), supports 12 chairs.", "price": 3800, "list_price": 4000, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/GIANT55 WITH DRYER image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "ENROLL-01", "description": "Youjoy Enroll-01 dental suction unit for a single-chair clinic. Suction capacity 300 L/min, AC-230V, 50 dB, 3440 rpm motor, 32 kg, 330x540x620 mm. Serves up to 1 chair, 1 in simultaneous use.", "price": 551, "list_price": 580, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Suction Unit", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/ENROLL-01 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "ENROLL-05", "description": "Youjoy Enroll-05 dental suction unit for a multi-chair clinic. Suction capacity 900 L/min, AC-230V, 59 dB, 3980 rpm motor, 33 kg, 410x510x610 mm. Serves up to 5 chairs, 3 in simultaneous use.", "price": 1520, "list_price": 1600, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Suction Unit", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/ENROLL-05 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "ENROLL-08", "description": "Youjoy Enroll-08 dental suction unit for a large clinic. Suction capacity 1500 L/min, AC-230V, 61 dB, 3740 rpm motor, 37 kg, 410x510x630 mm. Serves up to 8 chairs, 5 in simultaneous use.", "price": 1805, "list_price": 1900, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Suction Unit", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/ENROLL-08 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "ZIRCONIA Teeth Set", "description": "Zirconia teeth set for shade matching and restoration reference. Supplied free with every Scan11 (5 sets).", "price": 0, "list_price": 0, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Accessories", "product_code": None, "uom": None, "badge": "Item", "section": "machinery", "is_purchasable": False, "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Asus Vivo Book", "description": "Core i3 gen 13th \r\nRam 8 gb\r\nSSD 128 GB\r\nSCREEN 15.6 INCH FHD IPS", "price": 369, "list_price": 389, "discount": 20, "discount_type": "cash", "brand": "Asus", "category": "Computers", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Asus Vivo Book image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Ideapad Ryzen 5", "description": "Core Ryzen 5 7000 Series\r\nRam 8 gb\r\nSSD 256 GB\r\nSCREEN 15.6 INCH FHD", "price": 319, "list_price": 419, "discount": 100, "discount_type": "cash", "brand": "Lenovo", "category": "Computers", "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": True, "product_image": "/static/uploads/products/Lenovo Ideapad Ryzen 5 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Supragingical Prophylaxis Powder", "description": None, "price": 1, "list_price": 1, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": None, "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": False, "product_image": "/static/uploads/products/Supragingical Prophylaxis Powder image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Protective Radiation Apron", "description": None, "price": 1, "list_price": 1, "discount": 0, "discount_type": "percent", "brand": "Asus", "category": None, "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": False, "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Computer Bag", "description": None, "price": 1, "list_price": 1, "discount": 0, "discount_type": "percent", "brand": "Asus", "category": None, "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": False, "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Mouse Pad", "description": None, "price": 1, "list_price": 1, "discount": 0, "discount_type": "percent", "brand": "Asus", "category": None, "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": False, "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Mouse", "description": None, "price": 1, "list_price": 1, "discount": 0, "discount_type": "percent", "brand": "Asus", "category": None, "product_code": None, "uom": None, "badge": None, "section": "machinery", "is_purchasable": False, "product_image": None,
        "images": [],
        "free_items": [],
    },
]


MANUALS = [
    {"product": "LX16-PLUS", "title": "Usage Instructions", "description": "User manual and quick-start guide for the LX16-PLUS diode laser.", "manual_image": "/static/uploads/manuals/2491cd3b87f44d5dba20a59927fecfbe.png", "pdf": "/static/uploads/manuals/74c1618e56894bec97cf6deb3c1437d8.pdf"},
    {"product": "PT-A", "title": None, "description": None, "manual_image": "/static/uploads/manuals/d1d35c9322eb44a99618dd3146ddef1c.png", "pdf": "/static/uploads/manuals/9648edb0e84c497e83b23ebef40c962e.pdf"},
    {"product": "LX16-PLUS", "title": None, "description": None, "manual_image": None, "pdf": "/static/uploads/manuals/577e371c2f354928a540e25a1c266aed.pdf"},
]


PROMOTIONS = [
    {"promotion_name": "PTA Special Deal", "description": "PTA Special deal", "price": 2700, "old_price": 2669.5, "start_date": datetime(2026, 8, 19, 0, 0, 0, tzinfo=timezone.utc), "end_date": datetime(2026, 9, 19, 23, 59, 59, tzinfo=timezone.utc), "promotion_image": "/static/uploads/promotions/PTA Special Deal image.JPEG",
        "items": [
            {"product": "PT-A", "qty": 1},
            {"product": "Woodpecker Trolley", "qty": 1},
        ],
    },
]


SETS = [
    {"set_name": "X-Ray + i-Sensor H2 Set", "description": "Includes: i-Sensor H2, Laptop, X-ray, Table, Bag, Mouse, Mouse pad, Special clothes", "price": 1890, "old_price": 1879.5, "brand": "Woodpecker", "set_image": "/static/uploads/sets/X-Ray + i-Sensor H2 Set image.JPEG", "detail_image": None,
        "option_groups": [
            {"name": "Laptop", "choices": [{"product": "Asus Vivo Book", "qty": 1, "price_delta": None, "is_default": True}, {"product": "Lenovo Ideapad Ryzen 5", "qty": 1, "price_delta": 79, "is_default": False}]},
            {"name": "X-Ray", "choices": [{"product": "Smart Ray Pro", "qty": 1, "price_delta": None, "is_default": True}, {"product": "Smart Ray", "qty": 1, "price_delta": 60, "is_default": False}]},
        ],
        "items": [
            {"product": "Asus Vivo Book", "qty": 1},
            {"product": "i-Sensor H2", "qty": 1},
            {"product": "Smart Ray Pro", "qty": 1},
            {"product": "Trolley T3-2", "qty": 1},
            {"product": "Protective Radiation Apron", "qty": 1},
            {"product": "Computer Bag", "qty": 1},
            {"product": "Mouse", "qty": 1},
            {"product": "Mouse Pad", "qty": 1},
        ],
    },
]


# hashed_password is the bcrypt hash straight from the source database -
# the plaintext is not recoverable, so seeded accounts keep whatever
# password they had there.
USERS = [
    {"user_name": "Admin User", "email": "admin@store.dev", "hashed_password": "$2b$12$eBuWiKCC6ztNZBm8I1BoUOobNUVuFsMd/Q9j7yGieMT3roVwBujcK", "role_title": "Admin", "address": None, "phone_num": "fjgh", "user_image": "/static/uploads/users/b4174df2185d4c27819a65abd8cd621f.webp", "date_of_birth": "2000-07-04", "gender": "other", "user_management": True, "price_listing": True, "product_management": True, "customer_management": True, "admin": True, "is_active": True, "is_verified": True},
    {"user_name": "Staff User", "email": "staff@store.dev", "hashed_password": "$2b$12$xVtFksbNfCPHeVECKlAzmuWcHCOsJgaNFUH36.f/Jki44TQLTLlJy", "role_title": "Staff", "address": None, "phone_num": None, "user_image": None, "date_of_birth": None, "gender": None, "user_management": False, "price_listing": True, "product_management": False, "customer_management": False, "admin": False, "is_active": True, "is_verified": True},
]


CUSTOMERS = [
    {"customer_name": "Sample Customer", "email": "customer@store.dev", "hashed_password": "$2b$12$KrdjwyX/7R6cV8pr0A.S/OuBjWwcLsaY1i3/mbbm5jR0G2TNWYM8y", "address": None, "phone_num": None, "customer_image": None, "latitude": None, "longitude": None, "map_link": None, "date_of_birth": None, "gender": None, "access_permission": False, "is_active": True, "is_verified": True},
    {"customer_name": "VIP Customer", "email": "vip.customer@store.dev", "hashed_password": "$2b$12$dXf7XXOOF7hgtfRAoruaZeNy7gS8EbAmbdTGDbA4vY57B1AxG1eLm", "address": None, "phone_num": None, "customer_image": None, "latitude": 11.536209, "longitude": 104.954185, "map_link": "https://maps.app.goo.gl/FZTGpBubdiMr8LPh6", "date_of_birth": None, "gender": None, "access_permission": True, "is_active": True, "is_verified": True},
    {"customer_name": "Thay", "email": "realbunthai@gmail.com", "hashed_password": "$2b$12$yc0M2FC51D2AepiJBaq4ou9usjr8/Wkt1xQRMbBBNq0cYnGzbOLkS", "address": None, "phone_num": "+855 93718670", "customer_image": None, "latitude": 11.538801, "longitude": 104.904031, "map_link": "https://maps.app.goo.gl/4VARVCYJR28csr4B8", "date_of_birth": None, "gender": None, "access_permission": True, "is_active": True, "is_verified": True},
]


# Overrides only. A key absent here reads as its default from
# app/core/settings_spec.py, so this block being short is normal.
APP_SETTINGS = [
    {"key": "contact_email", "value": "engbongdev@gmail.com"},
    {"key": "document_tel_line", "value": "098 882 953"},
]


QR_CODES = [
    {"title": "Technician Support", "subtitle": "Technical Support Team", "qr_image": "/static/uploads/qr/technician-support.png", "badge_label": "Support", "badge_variant": "", "badge_icon": "fa-wrench", "sort_order": 1},
    {"title": "Machine Sale", "subtitle": "Sales Department - Machinery", "qr_image": "/static/uploads/qr/machine-sale.png", "badge_label": "Machinery", "badge_variant": "machinery", "badge_icon": "fa-gear", "sort_order": 2},
    {"title": "Material Sale", "subtitle": "Sales Department - Materials", "qr_image": "/static/uploads/qr/material-sale.png", "badge_label": "Materials", "badge_variant": "materials", "badge_icon": "fa-flask", "sort_order": 3},
    {"title": "Slock Implant", "subtitle": "Implant Department", "qr_image": "/static/uploads/qr/slock-implant.png", "badge_label": "Implants", "badge_variant": "implants", "badge_icon": "fa-tooth", "sort_order": 4},
]


HERO_SLIDES = [
    {"heading": "Come check our", "heading_highlight": "Materials", "subheading": "Discover high-quality dental materials from world-class brands trusted by professionals.", "slide_image": "/static/uploads/hero/9556efcbf60c4b12936f564d105ddff7.jpg", "badge_label": "Materials", "badge_icon": "fa-flask", "button_label": "Explore Materials", "button_url": "/materials", "is_active": True, "sort_order": 1},
]
