"""
Seed fixtures - GENERATED FILE, DO NOT EDIT BY HAND.

Exported from a live database on 2026-08-12 04:55 UTC by
`python -m scripts.export_seed_data`, and replayed by
`python -m scripts.seed_catalog`. Hand edits are lost the next time somebody
re-exports; change the data in the database and export again instead.

Every reference between tables is a natural key ("brand", "category",
"product" hold names, not ids) - see the module docstring in
scripts/export_seed_data.py for why.
"""
from datetime import datetime, timezone

BRANDS = [
    {"brand_name": "Woodpecker", "brand_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/brands/8aed9a7e49354c42ba01b398a2fa4305.png"},
    {"brand_name": "YouJoy", "brand_image": None},
]


CATEGORIES = [
    {"category_name": "Diode Laser System", "category_image": None},
    {"category_name": "Intraoral Scanner", "category_image": None},
    {"category_name": "Piezo Bone Surgery", "category_image": None},
    {"category_name": "Dental Implant Device", "category_image": None},
    {"category_name": "Dental Electric Motor", "category_image": None},
    {"category_name": "Air Polisher System", "category_image": None},
    {"category_name": "Endo Activator", "category_image": None},
    {"category_name": "Endo Motor", "category_image": None},
    {"category_name": "Gutta-purcha Obteration System", "category_image": None},
    {"category_name": "Curing Light", "category_image": None},
    {"category_name": "Ultrasonic Scaler", "category_image": None},
    {"category_name": "Air polisher", "category_image": None},
    {"category_name": "i-Sensor", "category_image": None},
    {"category_name": "Portable X-ray", "category_image": None},
    {"category_name": "Surgical Microscope Combo", "category_image": None},
    {"category_name": "Woodpecker Combo Set", "category_image": None},
    {"category_name": "KP-Oral Camera Combo Set", "category_image": None},
    {"category_name": "Laptop", "category_image": None},
    {"category_name": "Apex Locator", "category_image": None},
    {"category_name": "Student Kit", "category_image": None},
    {"category_name": "Trolley", "category_image": None},
    {"category_name": "Surgical Microscope", "category_image": None},
    {"category_name": "Intraoral Camera", "category_image": None},
    {"category_name": "Contra-angles", "category_image": None},
    {"category_name": "Contra-angles for implant Motor", "category_image": None},
    {"category_name": "Contra-angles Endo Motor", "category_image": None},
    {"category_name": "X Ray sensor Package", "category_image": None},
    {"category_name": "Color Shade Detector", "category_image": None},
    {"category_name": "Autoclave", "category_image": None},
    {"category_name": "Ultrasonic Cleaner", "category_image": None},
    {"category_name": "Dental Sensor", "category_image": None},
    {"category_name": "Water Distiller", "category_image": None},
    {"category_name": "Sealing Machine", "category_image": None},
    {"category_name": "Air Compressor", "category_image": None},
    {"category_name": "Mobile Cart", "category_image": None},
]


# "brand" / "category" are names resolved against BRANDS / CATEGORIES above.
# "images" are the EXTRA gallery photos only - the primary one is
# product_image. "free_items" name other products in this same list, so
# they are linked in a second pass once every product exists.
PRODUCTS = [
    {"product_name": "LX16-PLUS", "description": "Multi-purpose dental diode laser for soft tissue, perio, endo, implant, surgery, and pain therapy.", "price": 0.01, "list_price": 3480, "discount": 3479.99, "discount_type": "cash", "brand": "Woodpecker", "category": "Diode Laser System", "product_code": None, "uom": None, "badge": "new", "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/LX16-PLUS image.JPEG",
        "images": [
            "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/46ee5c1980324d1f80e37e24fba6b762.jpg",
            "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/03c482f335ae4b18bb767884caebb5db.png",
        ],
        "free_items": [
            {"product": "Woodpecker Trolley", "qty": 1},
            {"product": "Smart Ray Pro Combo H2", "qty": 1},
            {"product": "Lenovo Legion Core i7 (RTX 4060)", "qty": 1},
            {"product": "AI Ray Pro + KP Cam Pro Combo (All-in-One Chairside Imaging Package)", "qty": 1},
            {"product": "WJ-SG45CL (1:3)", "qty": 1},
        ],
    },
    {"product_name": "KP SmileScan", "description": "High-precision intraoral scanner with full-arch imaging, AI-enhanced accuracy, and seamless lab integration.", "price": 3372.5, "list_price": 3550, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Intraoral Scanner", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/KP SmileScan image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "US-II LED", "description": "Multi-function piezo ultrasonic scaler for scaling, perio, endo, implant maintenance, and surgery.", "price": 1425, "list_price": 1500, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Piezo Bone Surgery", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/US-II LED image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Implanter", "description": "Precision implant motor for implant placement, surgery, and torque control.", "price": 1235, "list_price": 1300, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Implant Device", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/Implanter image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Surgery-X", "description": "Piezoelectric surgical unit for bone surgery, soft tissue surgery, and implant placement with adjustable power and irrigation.", "price": 2470, "list_price": 2600, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Piezo Bone Surgery", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/Surgery-X image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "3 in 1 Surgic Star", "description": "3-in-1 premium implant and surgical motor with smart presets, touchscreen control, and stable irrigation.", "price": 3705, "list_price": 3900, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Implant Device", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/3 in 1 Surgic Star image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "ES5", "description": "High-performance multi-purpose electric motor for implant, surgical, and endodontic procedures, up to 120,000 rpm.", "price": 1520, "list_price": 1600, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Dental Electric Motor", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/ES5 image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "PT-A", "description": "Ultrasonic scaler and air polisher combo with heated water delivery and hands-free touchscreen control.", "price": 2470, "list_price": 2600, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Air Polisher System", "product_code": None, "uom": None, "badge": None, "product_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/products/PT-A image.JPEG",
        "images": [],
        "free_items": [],
    },
    {"product_name": "Endo 3", "description": "High-performance rotary endodontic system for root canal treatment, cleaning, and shaping.", "price": 171, "list_price": 180, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Activator", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Endo Radar Pro", "description": "Top-tier apex locator with advanced tracking technology for precise root canal measurement.", "price": 456, "list_price": 480, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "FI-G", "description": "Gutta percha obturation device with exceptional sealing performance and easy handling.", "price": 289.8, "list_price": 305.05, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Gutta-purcha Obteration System", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Motopex", "description": "Compact dental micromotor for precision drilling, root canal treatment, implantology, and crown prep.", "price": 399, "list_price": 420, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "FI-P", "description": "Gutta percha obturation device with superior adaptability and long-term reliability.", "price": 180.5, "list_price": 190, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Gutta-purcha Obteration System", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "E-COM+", "description": "Powerful cordless endomotor for canal cleaning and shaping with precise torque control.", "price": 275.5, "list_price": 290, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "R1-Plus", "description": "Precision endodontic measuring ruler for gutta percha cutting and working length measurement.", "price": 25, "list_price": 29.07, "discount": 14, "discount_type": "percent", "brand": "Woodpecker", "category": "Gutta-purcha Obteration System", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Endo Pace", "description": "Cordless brushless endomotor with apex locator integration for safe, efficient canal treatment.", "price": 256.5, "list_price": 270, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED H", "description": "Curing light, light intensity 1000-1800 mW/cm2.", "price": 104.5, "list_price": 110, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED F", "description": "Curing light, light intensity 1600-1800 mW/cm2.", "price": 128.3, "list_price": 135.05, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED G", "description": "Curing light, light intensity 1000-1200 mW/cm2.", "price": 66.5, "list_price": 70, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "LED B", "description": "Curing light, light intensity 1000-1700 mW/cm2.", "price": 54.4, "list_price": 68, "discount": 20, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "iLED II", "description": "Curing light, light intensity 2700-3000 mW/cm2.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "U-Light", "description": "Lightweight curing light with 3 modes and 360° rotation for consistent polymerization.", "price": 171, "list_price": 180, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "iLED MAX", "description": "Curing light, light intensity 2300-2500 mW/cm2.", "price": 116, "list_price": 119.59, "discount": 3, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "O-Star", "description": "High-performance curing light with 7 preset modes and 360° use for deep polymerization.", "price": 342, "list_price": 360, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "iLED Plus", "description": "Curing light, light intensity 2300-2500 mW/cm2.", "price": 95, "list_price": 100, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "X-Star", "description": "High-performance curing light with 8 preset modes and 360° use for deep polymerization.", "price": 494, "list_price": 520, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Curing Light", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "U600 LED", "description": "Advanced ultrasonic scaler with LED handpiece illumination and 3 modes (scaling, perio, endo).", "price": 332.5, "list_price": 350, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N3 LED", "description": "Built-in ultrasonic scaler with LED illumination and detachable autoclavable handpiece.", "price": 115, "list_price": 115, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-T LED", "description": "Multi-function ultrasonic scaler for scaling, perio, and endo with LED handpiece.", "price": 247, "list_price": 260, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N6", "description": "Compact built-in scaler for scaling, perio, and endo with auto frequency tracking.", "price": 179, "list_price": 179, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "USD-E LED", "description": "Precision ultrasonic scaler with adjustable power and bright LED illumination.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N3 LED Handpiece", "description": "Replacement handpiece for the UDS-N3 LED ultrasonic scaler.", "price": 69, "list_price": 69, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "UDS-N6 LED Handpiece", "description": "Replacement handpiece for the UDS-N6 LED ultrasonic scaler.", "price": 81, "list_price": 81, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Ultrasonic Scaler", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AP-H", "description": "High-performance dental air polisher for stain removal, whitening, prophylaxis, and implant cleaning.", "price": 179.6, "list_price": 189.05, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Air polisher", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "i-Sensor H2", "description": "High-resolution digital intraoral sensor for adult imaging with AI-enhanced diagnostics.", "price": 750.5, "list_price": 790, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "i-Sensor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro", "description": "High-speed 3D scanner for quality inspection, reverse engineering, and precision measurement.", "price": 665, "list_price": 700, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "i-Sensor H 1.5", "description": "High-resolution digital intraoral sensor for adult imaging with AI-enhanced diagnostics.", "price": 655.5, "list_price": 690, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "i-Sensor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Ray", "description": "AI-driven dental imaging system for diagnostics, treatment planning, and radiography.", "price": 845.5, "list_price": 890, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Ray Pro", "description": "AI positioning X-ray system that automatically detects and aligns the target for consistent imaging.", "price": 997.5, "list_price": 1050, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray", "description": "Portable DC X-ray system for intraoral imaging, endodontic diagnosis, and implant planning.", "price": 703, "list_price": 740, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro Combo H1.5", "description": "Smart Ray Pro + Sensor H1.5 + trolley + radiation apron + laptop bundle.", "price": 1790, "list_price": 1924.73, "discount": 7, "discount_type": "percent", "brand": "Woodpecker", "category": "Surgical Microscope Combo", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro Combo H2", "description": "Smart Ray Pro + Sensor H2 + trolley + radiation apron + laptop bundle.", "price": 1890, "list_price": 2032.26, "discount": 7, "discount_type": "percent", "brand": "Woodpecker", "category": "Surgical Microscope Combo", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Combo H1.5", "description": "Smart Ray + Sensor H1.5 + trolley + radiation apron + laptop bundle.", "price": 1850, "list_price": 1968.09, "discount": 6, "discount_type": "percent", "brand": "Woodpecker", "category": "Woodpecker Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Combo H2", "description": "Smart Ray + Sensor H2 + trolley + radiation apron + laptop bundle.", "price": 1950, "list_price": 2074.47, "discount": 6, "discount_type": "percent", "brand": "Woodpecker", "category": "Woodpecker Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Combo H1.5", "description": "AI Ray + Sensor H1.5 + trolley + radiation apron + laptop bundle.", "price": 1890, "list_price": 2123.6, "discount": 11, "discount_type": "percent", "brand": "Woodpecker", "category": "Woodpecker Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Combo H2", "description": "AI Ray + Sensor H2 + trolley + radiation apron + laptop bundle.", "price": 1990, "list_price": 2211.11, "discount": 10, "discount_type": "percent", "brand": "Woodpecker", "category": "Woodpecker Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Pro Combo H1.5", "description": "AI Ray Pro + Sensor H1.5 + trolley + radiation apron + laptop bundle.", "price": 2050, "list_price": 2277.78, "discount": 10, "discount_type": "percent", "brand": "Woodpecker", "category": "Woodpecker Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Pro Combo H2", "description": "AI Ray Pro + Sensor H2 + trolley + radiation apron + laptop bundle.", "price": 2150, "list_price": 2362.64, "discount": 9, "discount_type": "percent", "brand": "Woodpecker", "category": "Woodpecker Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Pro + KP Cam Pro Combo (All-in-One Chairside Imaging Package)", "description": "AI Ray Pro + i-Sensor H2 + KP Cam Pro + trolley all-in-one chairside imaging bundle, 2-year warranty.", "price": 2790, "list_price": 3032.61, "discount": 8, "discount_type": "percent", "brand": "Woodpecker", "category": "KP-Oral Camera Combo Set", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Ideapad (Core i3 Gen 13th, 8GB/128GB)", "description": "Laptop: Core i3 gen 13th, RAM 8GB, SSD 128GB, 15.6-inch FHD IPS.", "price": 369, "list_price": 388.42, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Ideapad Ryzen 5 (Ryzen5 7000 Series, 8GB/256GB)", "description": "Laptop: Ryzen 5 7000 series, RAM 8GB, SSD 256GB, 15.6-inch FHD.", "price": 419, "list_price": 517.28, "discount": 19, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Ideapad Ryzen 5 (Ryzen5 5000 Series, 8GB/256GB)", "description": "Laptop: Ryzen 5 5000 series, RAM 8GB, SSD 256GB, 15.6-inch FHD IPS.", "price": 448, "list_price": 546.34, "discount": 18, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Ideapad Core i5 (8GB/256GB)", "description": "Laptop: Core i5 gen 11th, RAM 8GB, SSD 256GB, 15.6-inch FHD IPS.", "price": 468, "list_price": 550.59, "discount": 15, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo ThinkBook Core i5", "description": "Laptop: Core i5 gen 11th, RAM 16GB, SSD 512GB, 15.6-inch FHD IPS.", "price": 548, "list_price": 668.29, "discount": 18, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Legion Core i7 (RTX 4060)", "description": "Laptop: Core i7 gen 14th, RAM 16GB, 512TB M2 SSD, GPU RTX 4060 8G, 15.6-inch high-performance IPS.", "price": 1249, "list_price": 1343.01, "discount": 7, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Lenovo Legion Core i7 (RTX 5060)", "description": "Laptop: Core i7 gen 14th, RAM 16GB, 1TB M2 SSD, GPU RTX 5060 8G, 15.6-inch high-performance IPS.", "price": 1449, "list_price": 1541.49, "discount": 6, "discount_type": "percent", "brand": "Woodpecker", "category": "Laptop", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Pex (Master Version)", "description": "Advanced AI-powered apex locator plus pulp testing function for precise root canal measurement.", "price": 361, "list_price": 380, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI-Pex", "description": "Advanced AI-powered apex locator plus pulp testing function for precise root canal measurement.", "price": 342, "list_price": 360, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Woodpex V", "description": "State-of-the-art apex locator ensuring accurate measurement for precise root canal treatments.", "price": 133, "list_price": 140, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Woodpex X", "description": "Compact, accurate apex locator for root canal length measurement and real-time canal monitoring.", "price": 180.5, "list_price": 190, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Apex Locator", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Mini-Pex", "description": "Portable, precise apex locator designed for accurate root canal measurement (student kit).", "price": 99, "list_price": 139.44, "discount": 29, "discount_type": "percent", "brand": "Woodpecker", "category": "Student Kit", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Tampered Glass Trolley", "description": "Mobile organized cart with 360° mobility, secure storage, and cable management; includes 2 free trays.", "price": 266, "list_price": 280, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "NW-A01", "description": "Mobile monitor cart with 360° mobility, secure storage, and cable management.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley 3-Drawer", "description": "Mobile organized cart with 360° mobility and secure storage; includes 2 free trays.", "price": 285, "list_price": 300, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley T3-4", "description": "Multi-layer mobile dental trolley with 3-tier storage, lockable wheels, medical-grade structure.", "price": 123.5, "list_price": 130, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Woodpecker Trolley", "description": "Mobile organized cart designed to support Woodpecker devices with 360° mobility.", "price": 199.5, "list_price": 210, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley T3-2", "description": "Multi-layer mobile dental trolley with 3-tier design, lockable wheels, medical-grade structure.", "price": 95, "list_price": 100, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Trolley NW-A03", "description": "Compact multi-drawer dental trolley with lockable wheels and flexible storage layout.", "price": 161.5, "list_price": 170, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 66x44mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 55.1, "list_price": 58, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 600mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 75.05, "list_price": 79, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 60x40mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 49.4, "list_price": 52, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 500mm", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 69.35, "list_price": 73, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 30x40mm (2-tier)", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 36.1, "list_price": 38, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 40x60mm (3-tier)", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 56.05, "list_price": 59, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Instrument Cart 30x40mm (3-tier)", "description": "Mobile organized cart with 360° mobility and secure storage.", "price": 45.6, "list_price": 48, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Trolley", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "KP iSee Pro", "description": "Premium surgical dental microscope with German SCHOTT optics, inclinable binocular tube, and integrated 4K imaging.", "price": 10600, "list_price": 10600, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Surgical Microscope", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "KP Cam Pro (Metal)", "description": "High-definition 1080P intraoral camera with one-click capture, true color reproduction, and 10 LED illumination.", "price": 940.5, "list_price": 990, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Intraoral Camera", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "KP Cam Pro (Plastic)", "description": "High-definition 1080P intraoral camera with one-click capture, true color reproduction, and 10 LED illumination.", "price": 750.5, "list_price": 790, "discount": 5, "discount_type": "percent", "brand": "Woodpecker", "category": "Intraoral Camera", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-45TL (1:5)", "description": "Contra-angle handpiece, gear ratio 1:5.", "price": 220, "list_price": 220, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-45L (1:4.2)", "description": "Contra-angle handpiece, gear ratio 1:4.2.", "price": 365, "list_price": 365, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "WJ-SG45CL (1:3)", "description": "Contra-angle handpiece, gear ratio 1:3.", "price": 340, "list_price": 340, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "WP-1L (20:1)", "description": "Contra-angle for implant motor, 20:1 reduction ratio, German bearing option available.", "price": 360, "list_price": 360, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles for implant Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "CA161 (6:1)", "description": "Contra-angle for endo motor, 6:1 reduction ratio.", "price": 169, "list_price": 169, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "CA001-G", "description": "Contra-angle for endo motor.", "price": 98, "list_price": 98, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Contra-angle Endo Motor (Woodpecker Bearing)", "description": "Contra-angle for endo motor with Woodpecker bearing option.", "price": 210, "list_price": 210, "discount": 0, "discount_type": "percent", "brand": "Woodpecker", "category": "Contra-angles Endo Motor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Pro Set Core i5", "description": "AI Ray Pro set including laptop (Core i5), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 2250, "list_price": 2528.09, "discount": 11, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Pro Set Core i3", "description": "AI Ray Pro set including laptop (Core i3), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 2150, "list_price": 2362.64, "discount": 9, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Set Core i5", "description": "AI Ray set including laptop (Core i5), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 2100, "list_price": 2359.55, "discount": 11, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "AI Ray Set Core i3", "description": "AI Ray set including laptop (Core i3), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 1990, "list_price": 2211.11, "discount": 10, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro Set Core i5 (Woodpecker)", "description": "Smart Ray Pro set including laptop (Core i5), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 2030, "list_price": 2182.8, "discount": 7, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro Set Core i3 (Woodpecker)", "description": "Smart Ray Pro set including laptop (Core i3), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 1930, "list_price": 2053.19, "discount": 6, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro Set Core i5", "description": "Smart Ray Pro set including laptop (Core i5), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 1990, "list_price": 2163.04, "discount": 8, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "Smart Ray Pro Set Core i3", "description": "Smart Ray Pro set including laptop (Core i3), H2 sensor, radiation apron, trolley, mouse and mouse pad.", "price": 1890, "list_price": 2032.26, "discount": 7, "discount_type": "percent", "brand": "Woodpecker", "category": "X Ray sensor Package", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "OMNI", "description": "Youjoy Omni Color Shade Detector for fast, accurate shade matching in crown, veneer, and restoration work.", "price": 266, "list_price": 280, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Color Shade Detector", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "SCAN11", "description": "Youjoy Scan11 Intraoral Scanner - fast 3D intraoral scanning with cloud functions for easy data storage and transfer.", "price": 2950, "list_price": 2950, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Intraoral Scanner", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "BES 22L-CLASS-B-LCD (Autoclave)", "description": "Youjoy BES-22L Class B LCD Autoclave sterilizer with clear LCD display for accurate, safe, and internationally compliant sterilization.", "price": 1580, "list_price": 1580, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "BES 23L-CLASS-B-LCD", "description": "Youjoy BES-23L Class B LCD Autoclave sterilizer with clear LCD display for accurate, safe, and internationally compliant sterilization.", "price": 1650, "list_price": 1650, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "BES 23L-CLASS-B-LED", "description": "Youjoy BES-23L Class B LED Autoclave sterilizer with LED display for accurate, safe, and internationally compliant sterilization.", "price": 1550, "list_price": 1550, "discount": 0, "discount_type": "percent", "brand": "YouJoy", "category": "Autoclave", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "UC-01", "description": "Youjoy Ultrasonic Cleaner UC-01 for fast, effective, and safe ultrasonic cleaning of dental instruments, jewelry, and medical tools. Capacity: 3 L.", "price": 179.55, "list_price": 189, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Ultrasonic Cleaner", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "CLEAN-02", "description": "Youjoy Ultrasonic Cleaner UC-02, an advanced ultrasonic cleaner for dental instruments, jewelry, and medical tools. Capacity: 6 L.", "price": 280.25, "list_price": 295, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Ultrasonic Cleaner", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "CLEAN-03", "description": "Youjoy Ultrasonic Cleaner UC-03, a high-performance ultrasonic cleaner for dental instruments, jewelry, and medical tools. Capacity: 7.5 L.", "price": 418, "list_price": 440, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Ultrasonic Cleaner", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "R2", "description": "Youjoy Sensor R2, a digital dental sensor for dental X-ray imaging.", "price": 655.5, "list_price": 690, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Dental Sensor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "DRINK (Water Distiller)", "description": "Youjoy Water Distiller (Model DRINK), a high-efficiency water distiller designed for dental clinics, medical offices, and laboratory use.", "price": 114, "list_price": 120, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Water Distiller", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "YOUJOY98P", "description": "Youjoy 98P Portable Dental X-Ray for diagnosis, implant, and endo work, offering clear imaging and precise, easy-to-use portable operation. Tube voltage 70KV+-10%, tube current 2mA+-20%, focus 0.4mm, exposure time range 0.04s-2.0s, machine weight 1.9kg.", "price": 560.5, "list_price": 590, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "SUPER05", "description": "Youjoy Super05 Portable X-Ray, a high-performance portable dental X-ray for diagnosis, endo, and implant planning. Tube voltage 70KV+-10%, tube current 2mA+-20%, focus 0.4mm, exposure time range 0.04s-2.0s, machine weight 1.7kg.", "price": 655.5, "list_price": 690, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Portable X-ray", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "SEAL120", "description": "Youjoy SEAL120 Sealing Machine, a reliable sterilization pouch sealing machine designed for dental and medical clinics.", "price": 152, "list_price": 160, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Sealing Machine", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "SEAL120 WITH RACK", "description": "Youjoy SEAL120 with rack Sealing Machine, a reliable sterilization pouch sealing machine designed for dental and medical clinics, including a rack.", "price": 170.05, "list_price": 179, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Sealing Machine", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT30", "description": "Runyes Giant-30 compact oil-free dental 100% dry air supply system designed for stable and hygienic airflow. Capacity 25 L, 1400 RPM, 0.6 rated power (KVA), supports 1 chair.", "price": 522.5, "list_price": 550, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT35", "description": "Runyes Giant-35 Air Compressor, a powerful dual-pump oil-free dental 100% dry air system for 1-2 chairs. Capacity 50 L, 1400 RPM, 1.2 rated power (KVA), supports 2 chairs.", "price": 845.5, "list_price": 890, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT40", "description": "Runyes Giant-40 Air Compressor, a high-capacity oil-free dental 100% dry air system for up to 3 chairs. Capacity 60 L, 1400 RPM, 1.54 rated power (KVA), supports 3 chairs.", "price": 997.5, "list_price": 1050, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT45", "description": "Runyes Giant-45 Air Compressor, a high-output oil-free dental 100% dry air system built for busy clinics. Capacity 70 L, 1400 RPM, 2.2 rated power (KVA), supports 5 chairs.", "price": 1282.5, "list_price": 1350, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT50", "description": "Runyes Giant-50 powerhouse oil-free 100% dry air compressor built for busy dental clinics. Capacity 135 L, 1400 RPM, 3.1 rated power (KVA), supports 8 chairs.", "price": 2185, "list_price": 2300, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "GIANT55", "description": "Runyes Giant-55 powerhouse oil-free 100% dry air compressor built for busy dental clinics. Capacity 210 L, 1400 RPM, 4.7 rated power (KVA), supports 12 chairs.", "price": 2755, "list_price": 2900, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Air Compressor", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "MOBILE CART TR/7A", "description": "TR-7A All-In-One Mobile Dental Cart, a sleek and versatile mobile workstation for digital dentistry with adjustable height, 3-layer tray design, 360-degree lockable wheels, and a built-in shelf for a laptop or scanner.", "price": 266, "list_price": 280, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Mobile Cart", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
    {"product_name": "TR/7A WORKSTATION CART", "description": "TR-7A All-In-One Mobile Dental Cart, a sleek and versatile mobile workstation for digital dentistry with adjustable height, 3-layer tray design, 360-degree lockable wheels, and a dedicated VESA-compatible monitor mount for a screen or digital scanner.", "price": 370.5, "list_price": 390, "discount": 5, "discount_type": "percent", "brand": "YouJoy", "category": "Mobile Cart", "product_code": None, "uom": None, "badge": "Item", "product_image": None,
        "images": [],
        "free_items": [],
    },
]


MANUALS = [
    {"product": "LX16-PLUS", "description": "User manual and quick-start guide for the LX16-PLUS diode laser.", "manual_image": None, "pdf": None},
]


PROMOTIONS = [
    {"promotion_name": "Summer Dental Sale", "description": "Seasonal discount bundle across select diode laser and scanner equipment.", "price": 2999, "old_price": None, "start_date": datetime(2026, 7, 27, 0, 0, 0, tzinfo=timezone.utc), "end_date": datetime(2026, 8, 26, 23, 59, 59, tzinfo=timezone.utc), "promotion_image": None,
        "items": [
            {"product": "KP SmileScan", "qty": 1},
            {"product": "Endo Pace", "qty": 1},
        ],
    },
]


SETS = [
    {"set_name": "Laptop Combo", "description": "ewrqwerwqerwqerqwd", "price": 2200, "old_price": None, "brand": None, "set_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/sets/Laptop Combo image.JPEG", "detail_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/sets/Laptop Combo detail image.JPEG",
        "items": [],
    },
    {"set_name": "Sensor 1.5 combo", "description": None, "price": 1890, "old_price": 1870, "brand": None, "set_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/sets/Sensor 1.5 combo image.JPEG", "detail_image": None,
        "items": [
            {"product": "i-Sensor H 1.5", "qty": 1},
            {"product": "AI-Ray", "qty": 1},
            {"product": "Lenovo Ideapad (Core i3 Gen 13th, 8GB/128GB)", "qty": 1},
            {"product": "LED H", "qty": 1},
        ],
    },
]


# hashed_password is the bcrypt hash straight from the source database -
# the plaintext is not recoverable, so seeded accounts keep whatever
# password they had there.
USERS = [
    {"user_name": "Admin User", "email": "admin@store.dev", "hashed_password": "$2b$12$eBuWiKCC6ztNZBm8I1BoUOobNUVuFsMd/Q9j7yGieMT3roVwBujcK", "role_title": "Admin", "address": None, "phone_num": "fjgh", "user_image": "https://pub-9e796b584d4340c79e93e11491a5f323.r2.dev/users/b4174df2185d4c27819a65abd8cd621f.webp", "date_of_birth": "2000-07-04", "gender": "other", "user_management": True, "price_listing": True, "product_management": True, "customer_management": True, "is_active": True, "is_verified": True},
    {"user_name": "Staff User", "email": "staff@store.dev", "hashed_password": "$2b$12$xVtFksbNfCPHeVECKlAzmuWcHCOsJgaNFUH36.f/Jki44TQLTLlJy", "role_title": "Staff", "address": None, "phone_num": None, "user_image": None, "date_of_birth": None, "gender": None, "user_management": False, "price_listing": False, "product_management": False, "customer_management": False, "is_active": True, "is_verified": True},
]


CUSTOMERS = [
    {"customer_name": "Sample Customer", "email": "customer@store.dev", "hashed_password": "$2b$12$KrdjwyX/7R6cV8pr0A.S/OuBjWwcLsaY1i3/mbbm5jR0G2TNWYM8y", "address": None, "phone_num": None, "customer_image": None, "date_of_birth": None, "gender": None, "access_permission": False, "is_active": True, "is_verified": True},
    {"customer_name": "VIP Customer", "email": "vip.customer@store.dev", "hashed_password": "$2b$12$dXf7XXOOF7hgtfRAoruaZeNy7gS8EbAmbdTGDbA4vY57B1AxG1eLm", "address": None, "phone_num": None, "customer_image": None, "date_of_birth": None, "gender": None, "access_permission": True, "is_active": True, "is_verified": True},
    {"customer_name": "Thay", "email": "realbunthai@gmail.com", "hashed_password": "$2b$12$yc0M2FC51D2AepiJBaq4ou9usjr8/Wkt1xQRMbBBNq0cYnGzbOLkS", "address": None, "phone_num": "+855 93718670", "customer_image": None, "date_of_birth": None, "gender": None, "access_permission": False, "is_active": True, "is_verified": True},
]
